### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: not a ZIP archive

### ISSUE THREAD

**Issue by Slashingbee** [eloialonso/diamond#25]
i followed the quick install guide (on windows) and i get the following error:

RuntimeError: PytorchStreamReader failed reading zip archive: not a ZIP archive

what can i do.

**Comment by Slashingbee** [comment]
any fixes? (for the csgo branch?)

**Comment by eloialonso** [comment]
Can you provide more details? In particular, what line causes that error? It looks like the checkpoint has not been completely downloaded.

**Comment by Slashingbee** [comment]
how to install the checkpoint? im on windows.

**Comment by AdamJelley** [comment]
Hi! We would still need more details to understand why you are getting that error, e.g. which file is not a ZIP archive. But since this is not an issue with the code, we created a [discord server](https://discord.gg/74vha5RWPg) for the community to discuss DIAMOND usage, including installation and training support. Please feel free to post your issue (including as much detail as possible on your setup and any error messages) and we'll plan to provide support there, and hope that the community may be able to help too!
