### ISSUE TITLE
Not using gpu

### ISSUE THREAD

**Issue by ShatteredOverlord** [eloialonso/diamond#26]
im using the csgo ai diffusion model and its only using my cpu

**Comment by Derzree** [comment]
yeah ive got the same problem im getting 100% usage on cpu and around 3% on gpu. what gpu do you have? ive got an amd 6750xt idk if thats the problem?

**Comment by eloialonso** [comment]
@ShatteredOverlord impossible to tell with such little detail. You have to make sure you have a cuda-enabled GPU and a working installation of PyTorch.

@Derzree I have no experience installing PyTorch for AMD GPUs. Looking at [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/), you have to make sure you have a ROCm-enabled GPU, and then use the command corresponding to your OS and package manager to install pytorch (provided on the same link).

**Comment by AdamJelley** [comment]
Hi! Please see the related issue #9 which may be helpful.

Otherwise, since this is not an issue with the code we created a [discord server](https://discord.gg/74vha5RWPg) for the community to discuss DIAMOND usage, including installation and training support. Please feel free to post your issue (including as much detail as possible on your setup and any error messages) and we'll plan to provide support there, and hope that the community may be able to help too!
