### ISSUE TITLE
instillation help

### ISSUE THREAD

**Issue by seeblo** [eloialonso/diamond#27]
can anyone help me run this, i downloaded the zip and extracted it, copied the command lines and pasted them into miniconda, but its not doing anything

**Comment by AdamJelley** [comment]
Hi! Since this is not an issue with the code, we created a [discord server](https://discord.gg/74vha5RWPg) for the community to discuss DIAMOND usage, including installation and training support. Please feel free to post your issue (including as much detail as possible on your setup and any error messages) and we'll plan to provide support there, and hope that the community may be able to help too!
