### ISSUE TITLE
The continuous action input and environmental changes

### ISSUE THREAD

**Issue by jiyuan-liu2000** [eloialonso/diamond#33]
I trained the diffusion world model using my own data, where the action inputs are continuous poses. However, after training, I found that the world model does not respond well to given action inputs. It usually just loops between certain actions, and there are significant environmental changes between consecutive frames. Could these issues be caused by insufficient training or data? Also, what are your thoughts on continuous action sequences as inputs? In the CSGO model, discrete inputs are used.

**Comment by AdamJelley** [comment]
Hi! Yes, those issues could be caused by insufficient data, particularly if there is a change in action distribution between the training data and the actions provided at test time. If the world model has not seen the effect of certain actions in certain states it may lead to modeling the effect of the modal action instead as you describe. For example, this can be the case when:
- The model is trained on random actions, but then played by a human at test time.
- The model is trained on expert data, but then more random actions are taken at test time (e.g. our CS:GO model does not accurately model random actions such as walking into a wall, since the human players do not often do this in the training data).

The significant environmental changes you describe between consecutive frames seems unusual, but could potentially be due to a bug in your data, for instance if the episode trajectories you provide are not contiguous in time. 

Regarding action inputs, our action inputs are discretized following the [CS:GO dataset](https://arxiv.org/abs/2104.04258) so we did not investigate continuous action inputs.

Hope that helps!
