### ISSUE TITLE
What is the reason of using `sigma_offset_noise`?

### ISSUE THREAD

**Issue by zhaoyi11** [eloialonso/diamond#36]
Thanks for the great work. I have a question about using `sigma_offset_noise=0.3` (https://github.com/eloialonso/diamond/blob/25ad7da9483936ae2b92b592f4315d9ac0bfb9d9/src/models/diffusion/denoiser.py#L67). I haven't seen the useage of this offset in the EDM paper (https://github.com/NVlabs/edm/blob/008a4e5316c8e3bfe61a62f874bddba254295afb/training/networks.py#L656) as well as the discussion in the paper. Would you mind explaining the motivation for using this offset?

Best,
Yi

**Comment by eloialonso** [comment]
Hi @zhaoyi11, thanks for the kind words and interesting question.

The intuition is that even high levels of independent gaussian noise do not completely destroy the low frequencies of the image (for instance if the image is globally dark, neutral or light). This means that during training, the diffusion model can almost always pick up the low frequencies from its input, and never has to create them from scratch. This is a problem at inference time, since we start from pure gaussian noise without any low-frequency structure. Adding offset noise during training is thus a way to have the model learn to modify the low frequencies.

Three remarks : 
- In the paper, the EDM versus DDPM comparison was realized with zero offset noise to really compare the benefits of the training objectives.
- From what we observed, this detail is not particularly important in Atari when using the EDM objective. 
- This trick was not introduced by us. To the best of our knowledge, this idea originates from [this blog post](https://www.crosslabs.org/blog/diffusion-with-offset-noise), which covers the above intuition in greater detail.
